version: '3.1'

services:
  mysql-db:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: R00tPa33w0rd!

  mysql-admin:
    image: adminer:4.7.7-standalone
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
